name: flutter_radio_player_workspace
description: Monorepo workspace for flutter_radio_player packages.
version: 4.0.0
homepage: https://github.com/Sithira/FlutterRadioPlayer
repository: https://github.com/Sithira/FlutterRadioPlayer

environment:
  sdk: '>=3.4.3 <4.0.0'
